
name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: aws-region-1

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # # Set up BuildKit Docker container builder to be able to build
      # # multi-platform images and export cache
      # # https://github.com/docker/setup-buildx-action
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     # registry: ghcr.io
      #     username: fiaplanches165
      #     password: dckr_pat_UOkG0z4dhWHcHLNorIIagEenaOw

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./fiap-lanches-clean/app
      #     push: true
      #     tags: fiaplanches165/fiaplanches:latest
